# Importing Libraries

In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

# Creating Dataset

In [4]:
dataset = tf.data.Dataset.range(10)

for val in dataset:
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9


# Creating Window Dataset

In [11]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5, shift=1)

for window_dataset in dataset:
  # print(window_dataset)
  for val in window_dataset:
    print(val.numpy(), end=' ')
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


# Drop Remainder (make each window same size)

In [12]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5, shift=1, drop_remainder=True)

for window_dataset in dataset:
  # print(window_dataset)
  for val in window_dataset:
    print(val.numpy(), end=' ')
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [20]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))

for window_dataset in dataset:
  print(window_dataset.numpy())

print(type(dataset))

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]
<class 'tensorflow.python.data.ops.dataset_ops.FlatMapDataset'>


# Create Features & Labels

In [23]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


# Shuffle & Create batches

In [24]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)

for x,y in dataset:
  print(x.numpy(), y.numpy())

[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]
[2 3 4 5] [6]
[1 2 3 4] [5]
[0 1 2 3] [4]


In [25]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size=5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)

for x,y in dataset:
  print(x.numpy(), y.numpy())

[[3 4 5 6]
 [4 5 6 7]] [[7]
 [8]]
[[5 6 7 8]
 [0 1 2 3]] [[9]
 [4]]
[[1 2 3 4]
 [2 3 4 5]] [[5]
 [6]]
